version: 2.1
jobs:
  test-image:
    machine: true
    environment:
      - IMAGE: makloj/django
      - NAME: django
      - PORT: 8000
    steps:
      - checkout
      - run:
          name: Build images
          working_directory: docker 
          command: docker build -t ${IMAGE} .
      - run:
          name: Start containers
          working_directory: builds
          command: docker run -itd --name ${NAME} -p ${PORT}:8000 ${IMAGE} sh
      - run:
          name: Integration test
          command: |
            set +e
            for i in [0..10]; do
              curl http://localhost:8000
              [[ $? -eq 0 ]] && { exit 0; } 
              sleep 3
            done
            exit 1
  push-image:
    machine: 
      image: ubuntu-2004:202010-01
    environment:
      - BUILDX: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
      - IMAGE: makloj/django
    steps:
      - checkout
      - run:
          name: Create directory for Docker Buildx plugin binary
          command: mkdir -vp ~/.docker/cli-plugins/
      - run:
          name: Login Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Download Buildx
          command: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx ${BUILDX}
      - run:
          name: Add permission to execute buildx
          command: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run:
          name: Create docker driver
          command: |
            docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
            docker buildx create --name circleci
            docker buildx use circleci
      - run:
          name: Build and Push docker image to Docker Hub
          working_directory: docker
          command: docker buildx build --platform linux/amd64,linux/arm64 -t ${IMAGE} --push .
workflows:
  version: 2.1
  django-pipeline:
    jobs:
      - test-image
      - push-image:
          requires:
            - test-image
          filters:
            branches:
              only: main
